### ISSUE TITLE
克隆项目 npm run start 报错

### ISSUE THREAD

**Issue by changfuguo** [ascoders/gaea-editor#51]

**Comment by changfuguo** [comment]
我是node10.10版本
克隆下来项目 运行 `npm run start'

报错

```
gaea-editor@2.3.19 start /Users/didi/Code/gaea-editor
> pri dev

✔ load plugins
(node:20910) UnhandledPromiseRejectionWarning: Error: component not support 'npm start' yet, try 'npm run docs'!
    at Object.<anonymous> (/Users/didi/Code/gaea-editor/node_modules/pri/built/built-in-plugins/command-dev/index.js:66:39)
    at step (/Users/didi/Code/gaea-editor/node_modules/pri/built/built-in-plugins/command-dev/index.js:32:23)
    at Object.next (/Users/didi/Code/gaea-editor/node_modules/pri/built/built-in-plugins/command-dev/index.js:13:53)
    at /Users/didi/Code/gaea-editor/node_modules/pri/built/built-in-plugins/command-dev/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/didi/Code/gaea-editor/node_modules/pri/built/built-in-plugins/command-dev/index.js:3:12)
    at action (/Users/didi/Code/gaea-editor/node_modules/pri/built/built-in-plugins/command-dev/index.js:50:49)
    at /Users/didi/Code/gaea-editor/node_modules/pri/built/bin.js:79:81
    at step (/Users/didi/Code/gaea-editor/node_modules/pri/built/bin.js:33:23)
    at Object.next (/Users/didi/Code/gaea-editor/node_modules/pri/built/bin.js:14:53)
(node:20910) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:20910) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

这个可能是什么原因呢?

**Comment by ascoders** [comment]
`npm run docs`

**Comment by jhoneybee** [comment]
源码不支持window 


![image](https://user-images.githubusercontent.com/24241052/58791839-8b455700-8625-11e9-9a6b-e5631d53bb4e.png)
